version: '3.8'

services:
  frontend:
    build: ./angular-frontend
    ports:
      - "${FRONTEND_PORT}:4200"
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - PORT=3000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
       - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:

